In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\Naveen\\Downloads\\HR_comma_sep.csv")

In [2]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [3]:
df.shape

(14999, 10)

In [4]:
df['left'].value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [5]:
feats = ['sales','salary']
df_final = pd.get_dummies(df,columns=feats,drop_first=True)

In [6]:
df_final.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

   sales_RandD  sales_accounting  sales_hr  sales_management  sales_marketing  \
0            0                 0         0                 0                0   
1            0                 0         0                 0                0   
2            0                 0         0                 0                0   
3            0                 0         0                 0                0   
4            0                 0         0                 0                0   

   sales_product_mng  sales_sales  sales_support  sales_technical  salary_low  \
0                  0            1              0                0           1   
1                  0            1              0                0           0   
2                  0            1              0                0           0   
3                  0            1              0                0           1   
4                  0            1              0                0           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

In [7]:
df_final.shape

(14999, 19)

In [8]:
df_final.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
sales_RandD              0
sales_accounting         0
sales_hr                 0
sales_management         0
sales_marketing          0
sales_product_mng        0
sales_sales              0
sales_support            0
sales_technical          0
salary_low               0
salary_medium            0
dtype: int64

# Separating Training and Testing Datasets

In [9]:
from sklearn.model_selection import train_test_split

use the left column in the dataset to predict if an employee will leave the company

In [10]:
X = df_final.drop(['left'],axis=1).values
y = df_final['left'].values
X

array([[0.38, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 0.  , 0.  , 1.  ],
       [0.11, 0.88, 7.  , ..., 0.  , 0.  , 1.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [11]:
y

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

# convert the dataset into a training and testing set. Use 70% of the data for training and 30% for testing

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=0)

# Transforming the Data

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the Artificial Neural Network

In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
classifier = Sequential()

W0828 11:37:22.503128 17384 deprecation_wrapper.py:119] From C:\Users\Naveen\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



Now start adding layers to our network

In [16]:
classifier.add(Dense(9, kernel_initializer = "uniform",activation = "relu", input_dim=18))

W0828 11:37:23.065368 17384 deprecation_wrapper.py:119] From C:\Users\Naveen\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0828 11:37:23.369270 17384 deprecation_wrapper.py:119] From C:\Users\Naveen\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



Add the output layer that will give the predictions:

In [17]:
classifier.add(Dense(1, kernel_initializer = "uniform",activation = "sigmoid"))

In [18]:
classifier.compile(optimizer= "adam",loss = "binary_crossentropy",metrics = ["accuracy"])

W0828 11:37:23.662193 17384 deprecation_wrapper.py:119] From C:\Users\Naveen\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0828 11:37:23.719873 17384 deprecation_wrapper.py:119] From C:\Users\Naveen\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0828 11:37:23.729322 17384 deprecation.py:323] From C:\Users\Naveen\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [19]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 10)

W0828 11:37:24.590562 17384 deprecation_wrapper.py:119] From C:\Users\Naveen\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/10
10499/10499 [==============================] - 3s 333us/step - loss: 0.4277 - acc: 0.7958
Epoch 2/10
10499/10499 [==============================] - 2s 155us/step - loss: 0.2654 - acc: 0.8527
Epoch 3/10
10499/10499 [==============================] - 2s 157us/step - loss: 0.2239 - acc: 0.9188
Epoch 4/10
10499/10499 [==============================] - 2s 152us/step - loss: 0.2031 - acc: 0.9514
Epoch 5/10
10499/10499 [==============================] - 2s 154us/step - loss: 0.1899 - acc: 0.9560
Epoch 6/10
10499/10499 [==============================] - 2s 163us/step - loss: 0.1811 - acc: 0.9558
Epoch 7/10
10499/10499 [==============================] - 2s 155us/step - loss: 0.1756 - acc: 0.9558
Epoch 8/10
10499/10499 [==============================] - 2s 153us/step - loss: 0.1716 - acc: 0.9543
Epoch 9/10
10499/10499 [==============================] - 2s 154us/step - loss: 0.1684 - acc: 0.9553
Epoch 10/10
10499/10499 [==============================] - 2s 152us/step - loss: 0.1661 - a

# Running Predictions on the Test Set

In [20]:
y_pred = classifier.predict(X_test)

In [21]:
y_pred 

array([[0.78401625],
       [0.01342493],
       [0.00211576],
       ...,
       [0.06993235],
       [0.0076405 ],
       [0.03777691]], dtype=float32)

In [22]:
y_pred = (y_pred > 0.5)

In [23]:
y_pred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Checking the Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_pred)
cm

array([[3355,  107],
       [ 104,  934]], dtype=int64)

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      3462
           1       0.90      0.90      0.90      1038

   micro avg       0.95      0.95      0.95      4500
   macro avg       0.93      0.93      0.93      4500
weighted avg       0.95      0.95      0.95      4500



We have evaluated our model using the confusion matrix

# Making a Single Prediction

In [26]:
new_pred = classifier.predict(sc.transform(np.array([[0.26,0.7 ,3., 238., 6., 0.,0.,0.,0., 0.,0.,0.,0.,0.,1.,0., 0.,1.]])))

In [27]:
new_pred

array([[0.01602093]], dtype=float32)

In [28]:
new_pred = (new_pred > 0.5)
new_pred

array([[False]])

You can see in the output that the employee won’t leave the company

In [29]:
new_pred = (new_pred > 0.6)
new_pred

array([[False]])

This new threshold still shows that the employee won’t leave the company

# Improving the Model Accuracy

In [30]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [31]:
def make_classifier():
    classifier = Sequential()
    classifier.add(Dense(9, kernel_initializer = "uniform", activation = "relu", input_dim=18))
    classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
    classifier.compile(optimizer= "adam",loss = "binary_crossentropy",metrics = ["accuracy"])
    return classifier

In [32]:
classifier = KerasClassifier(build_fn = make_classifier, batch_size=10, nb_epoch=1)

In [33]:
accuracies = cross_val_score(estimator = classifier,X = X_train,y = y_train,cv = 10,n_jobs = -1)

Now you have applied the cross-validation, you can compute the mean and variance of the accuracies

In [34]:
mean = accuracies.mean()
mean

0.8670378078638471

In [35]:
variance = accuracies.var()
variance

0.0009411248855580791

You see that the variance is 0.000941. Since the variance is very low, it means that your model is performing very well.